// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponsePayload.proto

package ca.NetSysLab.ProtocolBuffers;

public final class ResponsePayload {
  private ResponsePayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes serverResponse = 1;</code>
     */
    boolean hasServerResponse();
    /**
     * <code>required bytes serverResponse = 1;</code>
     */
    com.google.protobuf.ByteString getServerResponse();

    /**
     * <code>required int32 payloadSize = 2;</code>
     */
    boolean hasPayloadSize();
    /**
     * <code>required int32 payloadSize = 2;</code>
     */
    int getPayloadSize();
  }
  /**
   * Protobuf type {@code ResPayload}
   */
  public static final class ResPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResPayload)
      ResPayloadOrBuilder {
    // Use ResPayload.newBuilder() to construct.
    private ResPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResPayload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResPayload defaultInstance;
    public static ResPayload getDefaultInstance() {
      return defaultInstance;
    }

    public ResPayload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serverResponse_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              payloadSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.ResponsePayload.internal_static_ResPayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.ResponsePayload.internal_static_ResPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.class, ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.Builder.class);
    }

    public static com.google.protobuf.Parser<ResPayload> PARSER =
        new com.google.protobuf.AbstractParser<ResPayload>() {
      public ResPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResPayload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResPayload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERRESPONSE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString serverResponse_;
    /**
     * <code>required bytes serverResponse = 1;</code>
     */
    public boolean hasServerResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes serverResponse = 1;</code>
     */
    public com.google.protobuf.ByteString getServerResponse() {
      return serverResponse_;
    }

    public static final int PAYLOADSIZE_FIELD_NUMBER = 2;
    private int payloadSize_;
    /**
     * <code>required int32 payloadSize = 2;</code>
     */
    public boolean hasPayloadSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 payloadSize = 2;</code>
     */
    public int getPayloadSize() {
      return payloadSize_;
    }

    private void initFields() {
      serverResponse_ = com.google.protobuf.ByteString.EMPTY;
      payloadSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerResponse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayloadSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, serverResponse_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, payloadSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, serverResponse_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, payloadSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResPayload)
        ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.ResponsePayload.internal_static_ResPayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.ResponsePayload.internal_static_ResPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.class, ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverResponse_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.ResponsePayload.internal_static_ResPayload_descriptor;
      }

      public ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.getDefaultInstance();
      }

      public ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload build() {
        ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload buildPartial() {
        ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload result = new ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverResponse_ = serverResponse_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payloadSize_ = payloadSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload other) {
        if (other == ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload.getDefaultInstance()) return this;
        if (other.hasServerResponse()) {
          setServerResponse(other.getServerResponse());
        }
        if (other.hasPayloadSize()) {
          setPayloadSize(other.getPayloadSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerResponse()) {
          
          return false;
        }
        if (!hasPayloadSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.NetSysLab.ProtocolBuffers.ResponsePayload.ResPayload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString serverResponse_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes serverResponse = 1;</code>
       */
      public boolean hasServerResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes serverResponse = 1;</code>
       */
      public com.google.protobuf.ByteString getServerResponse() {
        return serverResponse_;
      }
      /**
       * <code>required bytes serverResponse = 1;</code>
       */
      public Builder setServerResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes serverResponse = 1;</code>
       */
      public Builder clearServerResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverResponse_ = getDefaultInstance().getServerResponse();
        onChanged();
        return this;
      }

      private int payloadSize_ ;
      /**
       * <code>required int32 payloadSize = 2;</code>
       */
      public boolean hasPayloadSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 payloadSize = 2;</code>
       */
      public int getPayloadSize() {
        return payloadSize_;
      }
      /**
       * <code>required int32 payloadSize = 2;</code>
       */
      public Builder setPayloadSize(int value) {
        bitField0_ |= 0x00000002;
        payloadSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 payloadSize = 2;</code>
       */
      public Builder clearPayloadSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payloadSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResPayload)
    }

    static {
      defaultInstance = new ResPayload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResPayload)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResPayload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ResponsePayload.proto\"9\n\nResPayload\022\026\n" +
      "\016serverResponse\030\001 \002(\014\022\023\n\013payloadSize\030\002 \002" +
      "(\005B/\n\034ca.NetSysLab.ProtocolBuffersB\017Resp" +
      "onsePayload"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ResPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResPayload_descriptor,
        new java.lang.String[] { "ServerResponse", "PayloadSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
